### ISSUE TITLE
Version 2.0 TODO list

### ISSUE THREAD

**Issue by evandrocoan** [evandrocoan/SublimeTextStudio#47]
1. [ ] ~Fix the Amxx Pawn Syntax, replacing the lookahead with recursive push/pop commented on:~
    * ~https://github.com/SublimeTextIssues/Core/issues/1799~
    * ~https://github.com/SublimeTextIssues/Core/issues/1796#issuecomment-312538775~
    Moved to: https://github.com/evandrocoan/SublimeTextStudio/issues/52 Fix the Amxx Pawn Syntax
1. [ ] ~Create the Channel manager, on the fork of the `ChannelRepositoryTools`.
Also, there is the `SublimeTextStudioChannel`. This one should call the
ChannelRepositoryTools and to inject its packages on the Package Control settings file.~ replaced by **update.py**
1. [ ] ~Release the Override Unpacked Packages on Package Control~ Moved to: https://github.com/evandrocoan/SublimeTextStudio/issues/53
1. [x] Search for shell scripts, python scrits to update your git repository fork.
1. [ ] ~Add all Sublimehq/Packages as a gitsubmodule. So they can be updated automatically 
when someone install the Studio not in development mode, i.e., only for end users.~ replaced by **update.py**
1. [ ] ~Complete the milestone Version 1.1.0 Release:~
https://github.com/evandrocoan/SublimeTextStudio/milestone/1
1. [ ] ~https://github.com/1egoman/backstroke/issues/62#issuecomment-319534443~
    > ~So as my URLs are public, anyone can create a simple script which start pinging repeatedly the same URL, over and over again for ever. This would cause GitHub to exhaust all my 6000 requests just for on repository URL, and can keep me blocking for ever from ping other repositories, as they are kicking off all my requests limit with the same repository.~

    ~Implement a hash table with the repositories as the key, so when performing check to the URL `https://backstroke.us/_dfasdf1asd1f3dsf32df...`, this table is checked and the time stamp is accessed and compared against the current time in EPOCH as 1501635118.~ deprecated, in favor of not publishing the URL keys.

___ 

Update

The script ~**update.py**~ (renamed to **submodules_manager.py**):

1. [ ] ~The package `Sublimehq/Packages` will be installed by the `Studio Channel`, and with the same procedure as the other packages.~
1. ~Is using the submodule `find_forks` to find all the repository forks and fetch their updates. After that, it remove all duplicated branches. Hence only remains the one which actually have changes. Also implement this:~
    1. [ ] ~https://github.com/frost-nzcr4/find_forks/issues/10 Count how many commits are the other forks ahead of the upstream~ Moved to https://github.com/evandrocoan/SublimeTextStudio/issues/55
1. Now all packages are going to be installed by git, if this option is chosen by the user, otherwise, they are installed like by package control, but using the URL's defined on the `.gitmodules`, instead of the URL's defined on the `package control default channel`. 
     Now the only package which can be installed by package control would be the `Studio Channel`, which will clone all the packages as git repositories or sublime-packages based on `.gitmodules` instead of the `Package Control.sublime-settings`, and also help user to: (**to do**)
    1. [ ] ~Fork the package from the original author~
    1. [ ] ~Set the Backstroke git webhook, so they can be notified of updates on the upstream.~
    1. [x] Now if the user want to use the version distributed by the Package Control, they just need to call a command on the Studio Channel package which will do this open the Package Control and uninstall it and then install it again. This also would remove the package from the `.gitmodules` file and put it on the `Package Control.sublime-settings` file as an installed package.
     It would delete the `unpackage` package on the Packages folder, and should stop the `Studio Channel` from downloading a new version, unless a command to reinstall it is issued. This command must not accept to install some package, if it is on the Package Control installed packages list. So, warn the user to uninstall the package.
    1. [x] On the installation process, warn/ask the user for the packages which are already installed, but are part of the Sublime Text Studio. Ask for the user to cancel the installation, or allow the packages to be uninstalled, and/or moved to disabled location.
    This would be the installation part make from the Package Control. This must be the same as a installation externally by git client cloning the Sublime Text Studio with the  `--recursive` option, where the difference would be it is from the package control would be keeping the user current settings.
     1. [x] New users should delete the `User` submodule after cloning the repository and place their user settings instead of mime. When installing this studio by package control, the user settings submodule must be ignored. Also installation steps should include the removal of the settings files when installing it directly by git or by package control on development mode.

**Comment by evandrocoan** [comment]
Moved the StudioChannel to Packages/StudioChannel as it will became

the package responsible to install the Sublime Text Studio, by
installing the PackagesManager and uninstalling Package Control,
installing the Channel Manager and calling it to install the Studio
Channel packages.

Also, will be responsible by the removal of Sublime Text Studio,
by calling the Channel Manager uninstaller and installing back
Package Control and removing PackagesManager.

**Comment by evandrocoan** [comment]
Completely split this into several smaller issues. Do not create big issues for next releases. Just create a milestone for the new release and add the issues into it.
